rvm:
  - 2.1
  - 2.0
  - 1.9
  - rbx-2
  - jruby

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby

addons:
  code_climate:
    repo_token:
      secure: Rl/y+wwpcx0NdqzvgnzmwXBMn1umbz81dQqtaLbthFqEF80a3SNJ0g3B5Z+FpRLaFNwaApcdcsiEK7G7H4APgxoKu7z/PdyHz+0pmzHhpxj9C8avPozy0sHCtBxE24HCYQqYeve29xYgBN6Mju+1y69VQKPr+yswE3/+chgAYdU=
